# Generated by Django 5.0.6 on 2024-07-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_ingredient_created_at_ingredient_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='restaurant_app.ingredient'),
        ),
    ]
