# Generated by Django 5.0.6 on 2024-08-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.recipe'),
        ),
    ]
