# Generated by Django 5.0.6 on 2024-08-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_purchase_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
