# Generated by Django 5.0.6 on 2024-08-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_purchase_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_cost',
        ),
    ]
